<?php
require_once($ROOT_DIR."/private/model/CharEntities.inc");
require_once($ROOT_DIR."/private/dao/CharEntitiesDAO.inc");
require_once($ROOT_DIR."/private/logic/CharEntitiesLogic.inc");

require_once($ROOT_DIR."/private/model/Entities.inc");
require_once($ROOT_DIR."/private/dao/EntitiesDAO.inc");
require_once($ROOT_DIR."/private/logic/EntitiesLogic.inc");

require_once($ROOT_DIR."/private/model/EntityPages.inc");
require_once($ROOT_DIR."/private/dao/EntityPagesDAO.inc");
require_once($ROOT_DIR."/private/logic/EntityPagesLogic.inc");

require_once($ROOT_DIR."/private/model/EntityTypes.inc");
require_once($ROOT_DIR."/private/dao/EntityTypesDAO.inc");
require_once($ROOT_DIR."/private/logic/EntityTypesLogic.inc");

?>
