<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> -->
    <meta name="keywords" content="<?php echo $tdl['keywords'] ?>">
    <meta name="description" content="<?php echo $tdl['description'] ?>">
    <title><?php echo $tdl['title'] ?></title> 
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/main.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/img/favicon.ico" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script data-main="/static/js/main" src="/static/js/require.2.1.20.min.js" defer async="true"></script>
    <script type="text/javascript">
    var isRelease=false;
    </script>
  
  </head>
  <body>
