<ul class="nav nav-pills">  
    <li role="presentation"><a href="/type/<?php echo $main['name']?>">概览</a></li> 
   <li role="presentation"><a href="/schema/<?php echo $main['name']?>">数据规范</a></li> 
   <li role="presentation"><a href="/download/<?php echo $main['name']?>">下载全量数据</a></li>
   <li role="presentation"><a href="/feed/<?php echo $main['name']?>">订阅每日更新</a></li>
   <li role="presentation"><a href="/upload?type=<?php echo $main['name']?>">上传数据</a></li> 
 </ul>